import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse as parseEnvFile } from "dotenv";
import { resolvePaperclipEnvPath } from "./paths.js";
import { logger } from "./middleware/logger.js";

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function renderEnvFile(entries: Record<string, string>): string {
  return [
    "# Paperclip environment variables",
    "# Generated by Paperclip server",
    ...Object.entries(entries).map(([k, v]) => `${k}=${formatEnvValue(v)}`),
    "",
  ].join("\n");
}

function readEnvEntries(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) return {};
  try {
    return parseEnvFile(readFileSync(filePath, "utf-8"));
  } catch {
    return {};
  }
}

/**
 * In local_trusted mode, mint and persist PAPERCLIP_AGENT_JWT_SECRET if absent.
 * Symmetric to how secrets/master.key is auto-provisioned on first boot.
 * Returns true when a new secret was minted this run.
 */
export function ensureLocalTrustedJwtSecret(): boolean {
  if (
    process.env.PAPERCLIP_AGENT_JWT_SECRET?.trim() ||
    process.env.BETTER_AUTH_SECRET?.trim()
  ) {
    return false;
  }

  const envPath = resolvePaperclipEnvPath();
  const existing = readEnvEntries(envPath);

  if (existing.PAPERCLIP_AGENT_JWT_SECRET?.trim()) {
    // Present in file but not loaded into env (edge-case: env file was written after config.ts ran).
    process.env.PAPERCLIP_AGENT_JWT_SECRET = existing.PAPERCLIP_AGENT_JWT_SECRET.trim();
    return false;
  }

  const secret = randomBytes(32).toString("hex");
  const merged = { ...existing, PAPERCLIP_AGENT_JWT_SECRET: secret };
  mkdirSync(path.dirname(envPath), { recursive: true });
  writeFileSync(envPath, renderEnvFile(merged), { mode: 0o600 });
  process.env.PAPERCLIP_AGENT_JWT_SECRET = secret;

  logger.info(
    `Auto-provisioned PAPERCLIP_AGENT_JWT_SECRET at ${envPath} (local_trusted mode, first boot)`,
  );

  return true;
}
